In [4]:
import pandas as pd

data = pd.read_csv('./train.csv',sep=',',dtype=object)
data.shape

(497819, 4)

In [5]:
data.head(10)

pair_id                                         name_1  \
0       1                            Iko Industries Ltd.   
1       2                        Apcotex Industries Ltd.   
2       3              Rishichem Distributors Pvt., Ltd.   
3       4                        Powermax Rubber Factory   
4       5                                      Tress A/S   
5       6                            Wpt Mexico Sa De Cv   
6       7                               National Bank Of   
7       8                            Citibank Korea Inc.   
8       9         Prettl Electric Del Bajio S.A. De C.V.   
9      10  Beijing Zhongyi Rongda Tech Trading Co., Ltd.   

                                 name_2 is_duplicate  
0  Enormous Industrial Trade Pvt., Ltd.            0  
1   Technocraft Industries (India) Ltd.            0  
2                                   Dsa            0  
3                               Co. One            0  
4      Longyou Industries Park Zhejiang            0  
5  Hopkins Mfg. De Mexico S De Rl De Cv            0  
6                  Action International            0  
7                                  Kyor            0  
8                              Bva Inc.            0  
9                N J International Inc.            0

In [6]:
data['name_1'].values[0:10]

array(['Iko Industries Ltd.', 'Apcotex Industries Ltd.',
       'Rishichem Distributors Pvt., Ltd.', 'Powermax Rubber Factory',
       'Tress A/S', 'Wpt Mexico Sa De Cv', 'National Bank Of',
       'Citibank Korea Inc.', 'Prettl Electric Del Bajio S.A. De C.V.',
       'Beijing Zhongyi Rongda Tech Trading Co., Ltd.'], dtype=object)

In [7]:
data_sub = data.sample(100)

In [8]:
import nltk
nltk.download()
from nltk.tokenize import word_tokenize

from parapply import parapply


data_sub['name_1_tokenized'] = parapply(data_sub['name_1'],lambda x: word_tokenize(text=x),n_jobs=4)
data_sub['name_2_tokenized'] = parapply(data_sub['name_2'],lambda x: word_tokenize(text=x),n_jobs=4)

showing info https://raw.githubusercontent.com/nltk/nltk_data/gh-pages/index.xml


/home/nikolaypavlychev/.local/lib/python3.10/site-packages/parapply/__init__.py:128: FutureWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  if type(obj) == type(pd.Series()):
/home/nikolaypavlychev/.local/lib/python3.10/site-packages/parapply/__init__.py:128: FutureWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  if type(obj) == type(pd.Series()):


In [9]:
data_sub

pair_id                        name_1  \
143730  143731      Rohit Rubber Corporation   
142856  142857                      Fns Inc.   
2766      2767                           Gap   
260516  260517                       Llc Itc   
179228  179229          Emulsion Product Co.   
...        ...                           ...   
374623  374624                       ATAB NV   
257314  257315                Khan Adil Ltd.   
355497  355498  Harrison Global Freight Inc.   
225043  225044        Afi International Inc.   
120242  120243      Corporacion Pok Sa De Cv   

                                           name_2 is_duplicate  \
143730                 Pentagon Rubber Pvt., Ltd.            0   
142856               Infinity Transportation Inc.            0   
2766          Guangzhou Ouyumei Trading Co., Ltd.            0   
260516          Alwadaah Trading And Services Co.            0   
179228  Pokharkar Engineering Products Pvt., Ltd.            0   
...                                           ...          ...   
374623                             INRECO EMULSJE            0   
257314                   Gkn Driveline Newton Llc            0   
355497                                   Rdis Srl            0   
225043          Saint Gobain Abrasives (Shanghai)            0   
120242         Corporacion Mitsuba De Mexico S.A.            0   

                           name_1_tokenized  \
143730         [Rohit, Rubber, Corporation]   
142856                        [Fns, Inc, .]   
2766                                  [Gap]   
260516                           [Llc, Itc]   
179228           [Emulsion, Product, Co, .]   
...                                     ...   
374623                           [ATAB, NV]   
257314                 [Khan, Adil, Ltd, .]   
355497  [Harrison, Global, Freight, Inc, .]   
225043         [Afi, International, Inc, .]   
120242       [Corporacion, Pok, Sa, De, Cv]   

                                         name_2_tokenized  
143730                [Pentagon, Rubber, Pvt., ,, Ltd, .]  
142856                 [Infinity, Transportation, Inc, .]  
2766        [Guangzhou, Ouyumei, Trading, Co., ,, Ltd, .]  
260516          [Alwadaah, Trading, And, Services, Co, .]  
179228  [Pokharkar, Engineering, Products, Pvt., ,, Lt...  
...                                                   ...  
374623                                  [INRECO, EMULSJE]  
257314                      [Gkn, Driveline, Newton, Llc]  
355497                                        [Rdis, Srl]  
225043         [Saint, Gobain, Abrasives, (, Shanghai, )]  
120242         [Corporacion, Mitsuba, De, Mexico, S.A, .]  

[100 rows x 6 columns]

In [10]:
from nltk.stem import SnowballStemmer 

stemmer = SnowballStemmer("english")

data_sub['name_1_stemmed'] = parapply(data_sub['name_1_tokenized'],lambda x: [stemmer.stem(i) for i in x],n_jobs=4)
data_sub['name_2_stemmed'] = parapply(data_sub['name_2_tokenized'],lambda x: [stemmer.stem(i) for i in x],n_jobs=4)

data_sub

/home/nikolaypavlychev/.local/lib/python3.10/site-packages/parapply/__init__.py:128: FutureWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  if type(obj) == type(pd.Series()):
/home/nikolaypavlychev/.local/lib/python3.10/site-packages/parapply/__init__.py:128: FutureWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  if type(obj) == type(pd.Series()):


pair_id                        name_1  \
143730  143731      Rohit Rubber Corporation   
142856  142857                      Fns Inc.   
2766      2767                           Gap   
260516  260517                       Llc Itc   
179228  179229          Emulsion Product Co.   
...        ...                           ...   
374623  374624                       ATAB NV   
257314  257315                Khan Adil Ltd.   
355497  355498  Harrison Global Freight Inc.   
225043  225044        Afi International Inc.   
120242  120243      Corporacion Pok Sa De Cv   

                                           name_2 is_duplicate  \
143730                 Pentagon Rubber Pvt., Ltd.            0   
142856               Infinity Transportation Inc.            0   
2766          Guangzhou Ouyumei Trading Co., Ltd.            0   
260516          Alwadaah Trading And Services Co.            0   
179228  Pokharkar Engineering Products Pvt., Ltd.            0   
...                                           ...          ...   
374623                             INRECO EMULSJE            0   
257314                   Gkn Driveline Newton Llc            0   
355497                                   Rdis Srl            0   
225043          Saint Gobain Abrasives (Shanghai)            0   
120242         Corporacion Mitsuba De Mexico S.A.            0   

                           name_1_tokenized  \
143730         [Rohit, Rubber, Corporation]   
142856                        [Fns, Inc, .]   
2766                                  [Gap]   
260516                           [Llc, Itc]   
179228           [Emulsion, Product, Co, .]   
...                                     ...   
374623                           [ATAB, NV]   
257314                 [Khan, Adil, Ltd, .]   
355497  [Harrison, Global, Freight, Inc, .]   
225043         [Afi, International, Inc, .]   
120242       [Corporacion, Pok, Sa, De, Cv]   

                                         name_2_tokenized  \
143730                [Pentagon, Rubber, Pvt., ,, Ltd, .]   
142856                 [Infinity, Transportation, Inc, .]   
2766        [Guangzhou, Ouyumei, Trading, Co., ,, Ltd, .]   
260516          [Alwadaah, Trading, And, Services, Co, .]   
179228  [Pokharkar, Engineering, Products, Pvt., ,, Lt...   
...                                                   ...   
374623                                  [INRECO, EMULSJE]   
257314                      [Gkn, Driveline, Newton, Llc]   
355497                                        [Rdis, Srl]   
225043         [Saint, Gobain, Abrasives, (, Shanghai, )]   
120242         [Corporacion, Mitsuba, De, Mexico, S.A, .]   

                             name_1_stemmed  \
143730              [rohit, rubber, corpor]   
142856                        [fns, inc, .]   
2766                                  [gap]   
260516                           [llc, itc]   
179228              [emuls, product, co, .]   
...                                     ...   
374623                           [atab, nv]   
257314                 [khan, adil, ltd, .]   
355497  [harrison, global, freight, inc, .]   
225043                [afi, intern, inc, .]   
120242       [corporacion, pok, sa, de, cv]   

                                      name_2_stemmed  
143730           [pentagon, rubber, pvt., ,, ltd, .]  
142856                    [infin, transport, inc, .]  
2766     [guangzhou, ouyumei, trade, co., ,, ltd, .]  
260516         [alwadaah, trade, and, servic, co, .]  
179228  [pokharkar, engin, product, pvt., ,, ltd, .]  
...                                              ...  
374623                              [inreco, emulsj]  
257314                  [gkn, drivelin, newton, llc]  
355497                                   [rdis, srl]  
225043        [saint, gobain, abras, (, shanghai, )]  
120242    [corporacion, mitsuba, de, mexico, s.a, .]  

[100 rows x 8 columns]

In [11]:
data_sub['name_1_stemmed_str'] = parapply(data_sub['name_1_stemmed'],lambda x: ' '.join(x),n_jobs=4)
data_sub['name_2_stemmed_str'] = parapply(data_sub['name_2_stemmed'],lambda x: ' '.join(x),n_jobs=4)


/home/nikolaypavlychev/.local/lib/python3.10/site-packages/parapply/__init__.py:128: FutureWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  if type(obj) == type(pd.Series()):
/home/nikolaypavlychev/.local/lib/python3.10/site-packages/parapply/__init__.py:128: FutureWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  if type(obj) == type(pd.Series()):


In [12]:
data_sub

pair_id                        name_1  \
143730  143731      Rohit Rubber Corporation   
142856  142857                      Fns Inc.   
2766      2767                           Gap   
260516  260517                       Llc Itc   
179228  179229          Emulsion Product Co.   
...        ...                           ...   
374623  374624                       ATAB NV   
257314  257315                Khan Adil Ltd.   
355497  355498  Harrison Global Freight Inc.   
225043  225044        Afi International Inc.   
120242  120243      Corporacion Pok Sa De Cv   

                                           name_2 is_duplicate  \
143730                 Pentagon Rubber Pvt., Ltd.            0   
142856               Infinity Transportation Inc.            0   
2766          Guangzhou Ouyumei Trading Co., Ltd.            0   
260516          Alwadaah Trading And Services Co.            0   
179228  Pokharkar Engineering Products Pvt., Ltd.            0   
...                                           ...          ...   
374623                             INRECO EMULSJE            0   
257314                   Gkn Driveline Newton Llc            0   
355497                                   Rdis Srl            0   
225043          Saint Gobain Abrasives (Shanghai)            0   
120242         Corporacion Mitsuba De Mexico S.A.            0   

                           name_1_tokenized  \
143730         [Rohit, Rubber, Corporation]   
142856                        [Fns, Inc, .]   
2766                                  [Gap]   
260516                           [Llc, Itc]   
179228           [Emulsion, Product, Co, .]   
...                                     ...   
374623                           [ATAB, NV]   
257314                 [Khan, Adil, Ltd, .]   
355497  [Harrison, Global, Freight, Inc, .]   
225043         [Afi, International, Inc, .]   
120242       [Corporacion, Pok, Sa, De, Cv]   

                                         name_2_tokenized  \
143730                [Pentagon, Rubber, Pvt., ,, Ltd, .]   
142856                 [Infinity, Transportation, Inc, .]   
2766        [Guangzhou, Ouyumei, Trading, Co., ,, Ltd, .]   
260516          [Alwadaah, Trading, And, Services, Co, .]   
179228  [Pokharkar, Engineering, Products, Pvt., ,, Lt...   
...                                                   ...   
374623                                  [INRECO, EMULSJE]   
257314                      [Gkn, Driveline, Newton, Llc]   
355497                                        [Rdis, Srl]   
225043         [Saint, Gobain, Abrasives, (, Shanghai, )]   
120242         [Corporacion, Mitsuba, De, Mexico, S.A, .]   

                             name_1_stemmed  \
143730              [rohit, rubber, corpor]   
142856                        [fns, inc, .]   
2766                                  [gap]   
260516                           [llc, itc]   
179228              [emuls, product, co, .]   
...                                     ...   
374623                           [atab, nv]   
257314                 [khan, adil, ltd, .]   
355497  [harrison, global, freight, inc, .]   
225043                [afi, intern, inc, .]   
120242       [corporacion, pok, sa, de, cv]   

                                      name_2_stemmed  \
143730           [pentagon, rubber, pvt., ,, ltd, .]   
142856                    [infin, transport, inc, .]   
2766     [guangzhou, ouyumei, trade, co., ,, ltd, .]   
260516         [alwadaah, trade, and, servic, co, .]   
179228  [pokharkar, engin, product, pvt., ,, ltd, .]   
...                                              ...   
374623                              [inreco, emulsj]   
257314                  [gkn, drivelin, newton, llc]   
355497                                   [rdis, srl]   
225043        [saint, gobain, abras, (, shanghai, )]   
120242    [corporacion, mitsuba, de, mexico, s.a, .]   

                   name_1_stemmed_str                    name_2_stemmed_str  
143730            rohit

In [18]:
train_texts = list(data_sub['name_1_stemmed_str'].values)+list(data_sub['name_2_stemmed_str'].values)

with open('./train_strings.csv','w') as f:
    for item in train_texts:
        f.writelines(item)
        f.writelines('\n')
    f.close()

In [19]:
import fasttext

print('train samples = ',len(train_texts))
model = fasttext.train_unsupervised(input='./train_strings.csv',model="skipgram", minn=2, maxn=5, dim=300,epoch=1, lr=0.5,thread=10)
model.words[0:10]


train samples =  200


Read 0M words
Number of words:  31
Number of labels: 0
Progress: 100.0% words/sec/thread:    1125 lr:  0.000000 avg.loss:  4.129757 ETA:   0h 0m 0s


['</s>', '.', 'ltd', 'de', 'industri', ',', 'co.', 'intern', 'inc', ')']

In [20]:
model.get_word_vector("industri")

array([ 4.48552251e-04,  2.25672426e-04, -7.68006139e-04, -3.81752761e-04,
       -3.44312924e-04,  1.97559624e-04, -2.62078946e-04, -2.66038347e-04,
        6.18231061e-05, -2.40936904e-04,  2.81751185e-04, -2.55512219e-04,
        2.28480552e-04, -2.57184147e-04,  1.72397806e-04,  5.49909542e-04,
        2.84845475e-04,  8.38399646e-05,  1.07437116e-03, -5.98062703e-04,
       -3.72522569e-04, -3.05502399e-05,  2.47273947e-05, -1.90107472e-04,
       -6.39238278e-04, -3.84229847e-04,  1.78925198e-04, -4.79197362e-04,
        2.29452227e-04,  1.69067513e-04,  2.87806732e-04, -4.18352633e-04,
        1.52190856e-04, -7.19877193e-04,  2.42133450e-04,  6.55678887e-05,
       -1.87378537e-04, -8.36341293e-04,  3.06873335e-05, -1.69385559e-04,
        4.35431924e-04,  9.48150482e-05,  1.38600924e-04, -2.70837161e-04,
       -3.36712896e-04, -6.41379680e-04,  6.52948394e-04, -2.10578481e-04,
       -5.48915472e-04, -1.53425659e-04,  8.46651310e-05,  1.51345021e-05,
       -3.29348928e-04, -

In [21]:
model.get_sentence_vector('total oil india privat limit , total')

array([-0.00310268,  0.02712183, -0.00909117,  0.00413302, -0.00891672,
        0.02224267, -0.01770647,  0.02702662, -0.02814972,  0.00893793,
       -0.00884809, -0.02641257,  0.04376266,  0.00178388,  0.05692641,
        0.01770771,  0.01097762, -0.01022951, -0.03078398, -0.01453605,
       -0.01008574, -0.0231733 ,  0.00839646,  0.04755497, -0.01103884,
       -0.01659429, -0.02586266, -0.0130047 , -0.01137896, -0.03807964,
       -0.00114988, -0.00925132, -0.03901032, -0.02954852, -0.03222671,
       -0.00085919, -0.01627375, -0.00619934,  0.04052476,  0.06044014,
        0.01083829, -0.01042003,  0.02072289,  0.02467722, -0.01472201,
       -0.00087855,  0.02289609, -0.03578279,  0.00914529,  0.02814726,
       -0.00050428, -0.03308293,  0.00804025, -0.03018698, -0.02178785,
       -0.00413669, -0.02953659,  0.043894  , -0.03798279, -0.02094945,
        0.00674168, -0.02856348, -0.02350471,  0.06176956, -0.02273437,
        0.00618541, -0.02631675,  0.03242731, -0.02413538, -0.00

In [31]:
import numpy as np

def cos_sim(a, b):
	dot_product = np.dot(a, b)
	norm_a = np.linalg.norm(a)
	norm_b = np.linalg.norm(b)
	return dot_product / (norm_a * norm_b)







In [30]:
import re

with open('./train_strings.csv','r') as f:
    train_texts_str = f.readlines()
    f.close()

train_texts_str_clear = []
for item in train_texts_str:
    train_texts_str_clear.append(item.replace("\n", ""))
train_texts_str_clear

['rohit rubber corpor',
 'fns inc .',
 'gap',
 'llc itc',
 'emuls product co .',
 'g.e . logist inc. g.e.forward',
 'pt bitratex industri',
 'utc',
 'pam sp a',
 'vohra chemic co .',
 'nuova banca etruria sp a',
 'qingdao free trade zone unit zhongqi logist co. , ltd .',
 'hexpol ab ( publ ) ( om : hpol b )',
 'adriatica bitumi spa',
 'w.a . intern',
 'chevron oronit brasil ltda',
 'emo tran inc .',
 'industria campin sas',
 'm & l worldwid logist',
 'parker industri de rl de cv',
 'lead car ( shanghai ) automot technolog co. , ltd .',
 'mwc de mexico s de rl de cv',
 'opti sourc s de rl de cv',
 'technovinyl polym india ltd .',
 'clifex industri ltd .',
 'tern packag',
 'world product imp . b.v .',
 'jim sport technolog s.l .',
 'katep',
 'iguasport ltda',
 'halliburton de mexico sa cv',
 'qingdao jiesen leather product co. , ltd .',
 'madesa s.a',
 'nagang imp . & exp . nz ltd .',
 'zamoung textil co .',
 'damco usa inc. 9300 arrowpoint blv',
 'i b intern',
 'jas forward de mexico s.

In [36]:
distances = np.zeros((len(train_texts_str_clear),len(train_texts_str_clear)),dtype=float)

for i, sentence_i in enumerate(train_texts_str_clear):
    for j, sentence_j in enumerate(train_texts_str_clear):
        vector_i = model.get_sentence_vector(sentence_i) 
        vector_j = model.get_sentence_vector(sentence_j)

        distances[i,j] = cos_sim(vector_i,vector_j)

distances

array([[ 1.        ,  0.049816  , -0.02690707, ...,  0.06301796,
         0.06910354,  0.18378091],
       [ 0.049816  ,  0.99999994, -0.02591458, ...,  0.07317615,
         0.13664441,  0.26400128],
       [-0.02690707, -0.02591458,  1.00000012, ...,  0.0601846 ,
        -0.01700344, -0.10413478],
       ...,
       [ 0.06301796,  0.07317615,  0.0601846 , ...,  1.        ,
         0.01919882, -0.05326067],
       [ 0.06910354,  0.13664441, -0.01700344, ...,  0.01919882,
         1.        ,  0.11744858],
       [ 0.18378091,  0.26400128, -0.10413478, ..., -0.05326067,
         0.11744858,  1.        ]])

In [43]:
np.fill_diagonal(distances,0)


In [44]:
distances

array([[ 0.        ,  0.049816  , -0.02690707, ...,  0.06301796,
         0.06910354,  0.18378091],
       [ 0.049816  ,  0.        , -0.02591458, ...,  0.07317615,
         0.13664441,  0.26400128],
       [-0.02690707, -0.02591458,  0.        , ...,  0.0601846 ,
        -0.01700344, -0.10413478],
       ...,
       [ 0.06301796,  0.07317615,  0.0601846 , ...,  0.        ,
         0.01919882, -0.05326067],
       [ 0.06910354,  0.13664441, -0.01700344, ...,  0.01919882,
         0.        ,  0.11744858],
       [ 0.18378091,  0.26400128, -0.10413478, ..., -0.05326067,
         0.11744858,  0.        ]])

In [47]:
distances_argmin = np.argmax(distances,axis=0)
distances_argmin

array([124,  67,  58, 188,  91, 118, 165,   3,  10, 142, 110, 111, 128,
       110, 150,  29, 101, 187, 189, 116,  70, 116, 116, 167, 156,  55,
        33,  57,  61, 147, 116,  69,  62,  85,  91, 151,  88, 137,  31,
       154,  23, 191, 123,  68,  78,  55,  61, 122,  83, 165, 116,  58,
        91, 103, 169,  73,  79,  94,  51, 179,  12,  46,  68,  49, 149,
        69, 166,   1,  62,  65, 120,  56, 172, 122,  83, 104, 120, 103,
        44,  67,  36,  94, 156,  48, 100, 161, 160, 126, 150, 118, 124,
       191, 141,  67,  81, 159, 147,   1, 150, 129,  84,  16,  70,  91,
       100,   3, 167, 177,  84, 100,  10, 148,  32,  91,  98, 191,  21,
        24,  67, 141,  70,  21, 163,  42,  90,   8,  70, 164,  12,  99,
        21,  91,  17,  33, 181,   3,  58,  37,   0, 190, 158,  92,   9,
        44, 140,  83, 147, 146, 111,  64,  98, 191, 154,  24,  88,  99,
        24,   3, 140, 154, 191,  85, 164, 122, 127,   6,   1, 106,  34,
        54,  91, 166,  23,   3,  69, 126, 100,  70, 184,  59,  8

In [46]:
train_texts_str_clear[0],train_texts_str_clear[124]

('rohit rubber corpor', 'lancor rubber industri')

In [48]:
train_texts_str_clear[1],train_texts_str_clear[67]

('fns inc .', 'apa industri inc .')

In [49]:
distances_min = np.max(distances,axis=0)
distances_min

array([0.43992835, 0.71505201, 0.28007209, 0.52400458, 0.6007117 ,
       0.57289678, 0.56729108, 0.25125062, 0.58053011, 0.63680947,
       0.6869995 , 0.70211792, 0.58347327, 0.32883802, 0.63576186,
       0.37889391, 0.67640698, 1.        , 0.5686655 , 0.77905411,
       0.79210812, 0.93510187, 0.82360667, 0.72665906, 0.80017924,
       0.36224967, 0.62950718, 0.52518052, 0.17956258, 0.38898569,
       0.64290005, 0.70255905, 0.48396018, 0.8364234 , 0.5839324 ,
       0.26098815, 0.5283128 , 0.76038778, 0.5518865 , 0.43185696,
       0.65406656, 0.62340683, 1.        , 0.27419338, 0.32189587,
       0.48879984, 0.42591769, 0.59636289, 0.46856278, 0.52916205,
       0.43872246, 0.51242495, 0.49269092, 0.22833623, 0.66478711,
       0.5521276 , 0.51652187, 0.67191195, 0.51242495, 0.6600787 ,
       0.26827443, 0.42591769, 0.71654212, 0.24033909, 0.75762498,
       0.75601608, 0.63030756, 0.71505201, 0.71654212, 0.75601608,
       0.8235178 , 0.26392081, 0.62731177, 0.61200368, 0.31498

In [50]:
train_texts_str_clear[17],train_texts_str_clear[distances_argmin[17]]

('industria campin sas', 'industria campin sas')